/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.views;
import br.com.views.ProdutosCadastro;
import br.com.views.ClientesCadastro;
import java.awt.Dimension;
import javax.swing.JFrame;
import javax.swing.JInternalFrame;

/**
 *
 * @author jorge.lrodrigues2
 */
public class Menu extends javax.swing.JFrame {

    private ProdutosCadastro produtoCadastro = null;
    private ClientesCadastro clienteCadastro = null;
    /**
     * Creates new form Principal
     */
    public Menu() {
        initComponents();
        //Faz com que a janela seja aberta no meio da tela
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        btnProdutoMenu = new javax.swing.JMenuItem();
        btnClienteMenu = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SoftInformatica");
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setIconImages(null);
        setMinimumSize(new java.awt.Dimension(500, 500));
        setResizable(false);

        jMenu1.setText("Cadastro");

        btnProdutoMenu.setText("Produto");
        btnProdutoMenu.setName("btnProduto"); // NOI18N
        btnProdutoMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProdutoMenuActionPerformed(evt);
            }
        });
        jMenu1.add(btnProdutoMenu);

        btnClienteMenu.setText("Cliente");
        btnClienteMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClienteMenuActionPerformed(evt);
            }
        });
        jMenu1.add(btnClienteMenu);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Faturamento");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Relatório");

        jMenuItem3.setText("Vendas");
        jMenu3.add(jMenuItem3);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 785, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 413, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnProdutoMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProdutoMenuActionPerformed
        // TODO add your handling code here:
        
        if (produtoCadastro == null || !produtoCadastro.isDisplayable()) {
            produtoCadastro = new ProdutosCadastro();
            produtoCadastro.pack();
            produtoCadastro.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            produtoCadastro.setLocationRelativeTo(null);
            produtoCadastro.setVisible(true);
        }
        produtoCadastro.toFront();
    }//GEN-LAST:event_btnProdutoMenuActionPerformed

    private void btnClienteMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClienteMenuActionPerformed
        // TODO add your handling code here:
        if (clienteCadastro == null || !clienteCadastro.isDisplayable()) {
            clienteCadastro = new ClientesCadastro();
            clienteCadastro.pack();
            clienteCadastro.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            clienteCadastro.setLocationRelativeTo(null);
            clienteCadastro.setVisible(true);
        }
        clienteCadastro.toFront();
    }//GEN-LAST:event_btnClienteMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem btnClienteMenu;
    private javax.swing.JMenuItem btnProdutoMenu;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem3;
    // End of variables declaration//GEN-END:variables
}
